### ISSUE TITLE
Terminal theme and fonts used in README.md

### ISSUE THREAD

**Issue by robmorgan** [charmbracelet/pop#18]
Very unimportant, but what combination of **terminal theme** and **font** are you using in your screenshots? 

![](https://camo.githubusercontent.com/4ad1dafd204924ad8fdcd5c0d17bcc7c56bf9e4abec75223271e89e2e1a769d1/68747470733a2f2f7668732e636861726d2e73682f7668732d354479763370767a423259777455537237324c71537a2e676966)

**Comment by maaslalani** [comment]
Hey! The font is JetBrains Mono: https://www.jetbrains.com/lp/mono/ and the terminal prompt is:

```
export PS1="\[\e[38;2;90;86;224m\]> \[\e[0m\]"
```

**Comment by maaslalani** [comment]
The terminal theme is: https://github.com/meowgorithm/dotfiles/blob/master/modules/home/colors.nix

**Comment by robmorgan** [comment]
@maaslalani cheers 👍
