### ISSUE TITLE
`brew install pop` doesn't install charmbracelet/pop

### ISSUE THREAD

**Issue by giann** [charmbracelet/pop#19]
**Describe the bug**
`brew install pop` doesn't install charmbracelet/pop but another software

**To Reproduce**
1. `brew install pop`
2. `$ pop`

**Comment by maaslalani** [comment]
Hey there! I cannot reproduce. Is your homebrew up-to-date?

```bash
brew update
```

https://formulae.brew.sh/formula/pop

**Comment by giann** [comment]
I'll try and update. Homebrew installed a .app some maybe its a cask? Or a tap i have.

**Comment by maaslalani** [comment]
Yes I believe there is a cask with the same name, but if you don't specify to install the cask it should install the formula. I believe since your homebrew might not have the formula so it would have installed the cask as a fallback.

**Comment by giann** [comment]
`brew update` fixed the issue
