### ISSUE TITLE
status code issue for the 0.2.0 release

### ISSUE THREAD

**Issue by chenrui333** [charmbracelet/pop#21]
**Describe the bug**

Looks like for the 0.2.0 release, the status code for missing `RESEND_API_KEY` is wrong, instead of reporting `1`, it reports `0`

relates to https://github.com/Homebrew/homebrew-core/pull/138222

**To Reproduce**
1. Install latest pop 0.2.0
2. `pop --body 'hi' --subject 'Hello'`
3. check the status code

**Comment by maaslalani** [comment]
Thanks I will fix this now

**Comment by maaslalani** [comment]
Fixed: https://github.com/charmbracelet/pop/commit/65b34a366addd90a9d4da32ac8e5d22268ec16bd

**Comment by chenrui333** [comment]
thanks for the quick turnaround, let me try the patch.

**Comment by chenrui333** [comment]
works for me, thanks for the quick fix. 🙏
