### ISSUE TITLE
SMTP username takes priority over from argument

### ISSUE THREAD

**Issue by Birdie0** [charmbracelet/pop#24]
**Describe the bug**
When having set both 'SMTP username' and 'from address' (through ENV variables or arguments) username takes priority.

**To Reproduce**
1. Run command: `pop --smtp.host localhost --smtp.port 25 --smtp.username test --smtp.password hunter2 --from test@example.com`

**Expected behavior**
From should be prefilled with `test@example.com`, instead there's `test` as value of `--smtp.username`

**Screenshots**
![image](https://github.com/charmbracelet/pop/assets/7945905/df9179a4-e21b-487f-9548-a7b7b7070ea6)

**Desktop:**
 - OS: Win11, WSL2
 - Version: 0.2.0

**Additional context**

**Comment by angelnext** [comment]
Has there been any progress?

**Comment by maaslalani** [comment]
Fixed by #36, thanks for the ping @angelnext!
