### ISSUE TITLE
 [ERROR]: The gmail.com domain is not verified.

### ISSUE THREAD

**Issue by ashishbinu** [charmbracelet/pop#27]
**Describe the bug**
Pop is not working with gmail. It is showing this error 
```
 [ERROR]: The gmail.com domain is not verified. Please, add and verify your domain on https://resend.com/domains
 ```

**To Reproduce**
1. Install pop
2. Setup env variables
```bash
export RESEND_API_KEY="$(pass api/resend)"
export POP_FROM="public.email@gmail.com"
export POP_SMTP_HOST=smtp.gmail.com
export POP_SMTP_PORT=587
export POP_SMTP_USERNAME="public.email@gmail.com"
export POP_SMTP_PASSWORD="password"
```
3. Send mail using `pop` command.
4. When pressing enter it shows the error

**Expected behavior**
I believe it should send email without showing the error.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 6.4.9-arch1-1

**Comment by ashishbinu** [comment]
I also tried adding gmail.com as suggested in the error. But it shows can't add public domains error in the dashboard.

**Comment by caarlos0** [comment]
Hey!

You don't need to set `RESEND_API_KEY` if you are using SMTP, so probably unexporting that env should fix the issue.

**Comment by ashishbinu** [comment]
> Hey!
> 
> You don't need to set `RESEND_API_KEY` if you are using SMTP, so probably unexporting that env should fix the issue.

![image](https://github.com/charmbracelet/pop/assets/56691622/925e58a3-e8b0-456a-8208-662c02bd2420)

It says the api key is required

**Comment by caarlos0** [comment]
@ashishbinu if you have the `POP_SMTP_*` environments set, it should not give you that error.

**Comment by ashishbinu** [comment]
@caarlos0 It's working now. As I had 2 factor authentication enabled had to create app password from google and replace the `POP_SMTP_PASSWORD` with that app password.
