### ISSUE TITLE
`--bcc strings` is not working

### ISSUE THREAD

**Issue by hellopq** [charmbracelet/pop#42]
Send with `--bcc` set, but not receieved, and on resend.com logs the bcc is still empty.

**Comment by hellopq** [comment]
BCC recipients

**Comment by maaslalani** [comment]
Hey @hellopq, are you using the TUI or the CLI to send `bcc`?

**Comment by maaslalani** [comment]
Hey @hellopq, we now support BCC + CC fields, let me know if everything is working for you:
* #65
