### ISSUE TITLE
Pass command not found

### ISSUE THREAD

**Issue by FBDev64** [charmbracelet/pop#55]
Pass command not found :

[fbdev@arch pop]$ export RESEND_API_KEY=$(pass XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX)
bash: pass: command not found
[fbdev@arch pop]$ export XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=$(pass RESEND_API_KEY)
bash: pass: command not found

**Comment by meowgorithm** [comment]
It looks like `pass` can't be found on your path. I'm going to close this as it's unrelated to `pop`, but we're more than happy to help point you in the right direction if you want to hop in [Charm Discord](https://charm.sh/discord) and chat.
