### ISSUE TITLE
POP_FROM ignored on POP_SMTP Config

### ISSUE THREAD

**Issue by fredbsc** [charmbracelet/pop#68]
**Describe the bug**
Default FROM is userid not email. Error on send - is not a valid mail-address. 
I'ts also not possible to set it as falg: pop -f (--from) my@example.com

My UserID != Mailaddress

export POP_FROM=my@example.com
export POP_SIGNATURE="Sent with pop from cli ..."
export POP_SMTP_HOST=server
export POP_SMTP_PORT=587
export POP_SMTP_USERNAME=myuserid
export POP_SMTP_PASSWORD=$(pass Mail/my/pass)

$pop
From: myuserid
TO: ....

##

$ echo $POP_FROM
my@example.com
$ echo $POP_SMTP_USERNAME
myuserid

**Desktop (please complete the following information):**
 - OS: ARCH Linux
 - pop -v 0.2.0

**Comment by fredbsc** [comment]
Sorry! This was the version from AUR. The build from your repo works like a charm!

**Comment by maaslalani** [comment]
Thank you for creating the issue and following up. Hope you're enjoying `pop`!
