### ISSUE TITLE
Missing AUR Package

### ISSUE THREAD

**Issue by Tarbolin69** [charmbracelet/pop#7]
Despite the instructions on the README, no package by the name of "pop" can be found in the AUR. Trying "pop-bin" instead only returns an unrelated screen-sharing app.

**Comment by maaslalani** [comment]
is `pop` taken?
https://aur.archlinux.org/packages/pop

**Comment by caarlos0** [comment]
packages from binaries need to have the `-bin` suffix: https://wiki.archlinux.org/title/AUR_submission_guidelines

**Comment by Tarbolin69** [comment]
Same as with the "Nix (coming soon)" disclaimer, shouldn't the same be done for the arch install bit until pop is released to the AUR?

**Comment by maaslalani** [comment]
Package is available as `charm-pop-bin`, updated the readme! Thanks @Tarbolin69
